# Ml Problem Life-Cycle
- Problem Understanding
- Data Collection
- Data Understanding
- Data Processing
- Model Building & Training
- Model Evaluation
- Model Selection
- Model Development
- Model Monitoring

## Problem:
- Ice-cream sale prediction based on temperature
- Dataset: icecream_sales_dataset.csv
- Model: Simple Linear Regression

In [1]:
# Installation 
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\user\anaconda3\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.8.0 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
# Import 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 
from sklearn import metrics

In [15]:
# load data
data = pd.read_csv(r"C:\Users\User\Downloads\icecream_sales_dataset (2).csv")
data.head()

   Temperature_C  IceCream_Sales
0      30.523830      875.871197
1      26.956777      810.412847
2      36.489760     1109.021413
3      23.796323      710.135154
4      15.308535      472.521514

In [17]:
# Data back-up
df = data.copy()

In [19]:
# Meta-data
print("No. of rows: ", df.shape[0])
print("No. of columns: ", df.shape[1])
print("All colums ", df.columns)
print("Overall info :\n")
df.info()

No. of rows:  10020
No. of columns:  2
All colums  Index(['Temperature_C', 'IceCream_Sales'], dtype='object')
Overall info :

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10020 entries, 0 to 10019
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Temperature_C   10010 non-null  float64
 1   IceCream_Sales  10010 non-null  float64
dtypes: float64(2)
memory usage: 156.7 KB

### Data Preprocessing 
- Data Type
- Duplicate
- Null Value
- Data Reduction
- Outliers
- Feature Engineering
- Scaling & Normalization
- Encoding
- Train-test Split

In [22]:
# Duplicate 
print("Total duplicate count: ", df.duplicated().sum())
print("Duplicate rows: \n")
df[df.duplicated()]

Total duplicate count:  20
Duplicate rows:

      Temperature_C  IceCream_Sales
1457      17.440463      519.788776
3917      30.817654      924.451385
3922      29.778543      931.610047
4273      26.644971      794.960889
4324      22.423889      663.418223
5377      25.574431      782.456790
5404      25.124311      777.073261
6010      22.010713      654.411788
6296      23.935782      706.354443
6392      43.842527     1331.176249
7658      27.068840      808.021404
7788      19.841021      615.974052
7886      16.067707      477.313778
8229      32.313512      938.590218
8249      29.094130      890.988340
8562      19.412204      585.416650
8591      39.696791     1163.216160
9324      34.283322     1030.716400
9707      33.716875     1009.560030
9747      38.265159     1133.969886

In [24]:
# Remove duplicate 
df.drop_duplicates(inplace = True)
print("Total duplicate count: ", df.duplicated().sum())

Total duplicate count:  0

In [26]:
# Null Values
df.isnull().sum()

Temperature_C     10
IceCream_Sales    10
dtype: int64

In [27]:
# Drop null
df.dropna(inplace = True)
df.isnull().sum()

Temperature_C     0
IceCream_Sales    0
dtype: int64

In [29]:
# Descriptive Statistics 
df.describe()

       Temperature_C  IceCream_Sales
count    9980.000000     9980.000000
mean       29.822430      894.914653
std         8.631672      259.482712
min        15.000349      386.278839
25%        22.379677      670.641581
50%        29.775593      894.783493
75%        37.214534     1115.580714
max        44.991530     1395.058842

In [30]:
#EDA

In [32]:
# Feature & Target
X = df.drop(columns = ["IceCream_Sales"])
y = df["IceCream_Sales"]

# Train-test-split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2, random_state = 42)

In [33]:
# Train and Test shape 
print("Training dataset shape: ", X_train.shape)
print("Test dataset shape: ", X_test.shape)

Training dataset shape:  (7984, 1)
Test dataset shape:  (1996, 1)

In [34]:
# Model Training 
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [35]:
# Prediction 
y_pred = model.predict(X_test)
df_predict = pd.DataFrame({"Actual" : y_test, "Prediction": y_pred})
df_predict.head(10)

           Actual   Prediction
1256  1172.998845  1181.120156
8255   545.878857   592.101968
1662  1062.873181  1058.641167
7759  1042.490855  1042.442859
1444   495.767249   466.955083
1059  1106.610267  1090.910982
35    1204.757399  1188.703707
7174   824.931234   837.706840
1666  1284.483239  1272.203332
4055   625.665337   659.771506